# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vmc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vmc.proto',
  package='org.ga4gh.vmc',
  syntax='proto3',
  serialized_pb=_b('\n\tvmc.proto\x12\rorg.ga4gh.vmc\"2\n\nIdentifier\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x11\n\taccession\x18\x02 \x01(\t\"(\n\x08Sequence\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08sequence\x18\x02 \x01(\t\"X\n\x12SequenceIdentifier\x12\x13\n\x0bsequence_id\x18\x01 \x01(\t\x12-\n\nidentifier\x18\x02 \x01(\x0b\x32\x19.org.ga4gh.vmc.Identifier\"&\n\x08Interval\x12\r\n\x05start\x18\x01 \x01(\x04\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x04\"w\n\x08Position\x12*\n\x04type\x18\x01 \x01(\x0e\x32\x1c.org.ga4gh.vmc.Position.Type\x12)\n\x08interval\x18\x02 \x01(\x0b\x32\x17.org.ga4gh.vmc.Interval\"\x14\n\x04Type\x12\x0c\n\x08INTERVAL\x10\x00\"V\n\x08Location\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0bsequence_id\x18\x02 \x01(\t\x12)\n\x08position\x18\x03 \x01(\x0b\x32\x17.org.ga4gh.vmc.Position\">\n\x06\x41llele\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0blocation_id\x18\x02 \x01(\t\x12\x13\n\x0breplacement\x18\x03 \x01(\t\"i\n\tHaplotype\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0bsequence_id\x18\x02 \x01(\t\x12\'\n\x07\x63ontext\x18\x03 \x01(\x0e\x32\x16.org.ga4gh.vmc.Context\x12\x12\n\nallele_ids\x18\x04 \x03(\t\"-\n\x08Genotype\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\rhaplotype_ids\x18\x02 \x03(\t*5\n\x07\x43ontext\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0f\n\x0bUNSPECIFIED\x10\x01\x12\x0c\n\x08\x43OMPLETE\x10\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_CONTEXT = _descriptor.EnumDescriptor(
  name='Context',
  full_name='org.ga4gh.vmc.Context',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPLETE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=679,
  serialized_end=732,
)
_sym_db.RegisterEnumDescriptor(_CONTEXT)

Context = enum_type_wrapper.EnumTypeWrapper(_CONTEXT)
UNKNOWN = 0
UNSPECIFIED = 1
COMPLETE = 2


_POSITION_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='org.ga4gh.vmc.Position.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INTERVAL', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=351,
  serialized_end=371,
)
_sym_db.RegisterEnumDescriptor(_POSITION_TYPE)


_IDENTIFIER = _descriptor.Descriptor(
  name='Identifier',
  full_name='org.ga4gh.vmc.Identifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespace', full_name='org.ga4gh.vmc.Identifier.namespace', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accession', full_name='org.ga4gh.vmc.Identifier.accession', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=78,
)


_SEQUENCE = _descriptor.Descriptor(
  name='Sequence',
  full_name='org.ga4gh.vmc.Sequence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='org.ga4gh.vmc.Sequence.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='org.ga4gh.vmc.Sequence.sequence', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=120,
)


_SEQUENCEIDENTIFIER = _descriptor.Descriptor(
  name='SequenceIdentifier',
  full_name='org.ga4gh.vmc.SequenceIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence_id', full_name='org.ga4gh.vmc.SequenceIdentifier.sequence_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='identifier', full_name='org.ga4gh.vmc.SequenceIdentifier.identifier', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=210,
)


_INTERVAL = _descriptor.Descriptor(
  name='Interval',
  full_name='org.ga4gh.vmc.Interval',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='org.ga4gh.vmc.Interval.start', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='org.ga4gh.vmc.Interval.end', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=250,
)


_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='org.ga4gh.vmc.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='org.ga4gh.vmc.Position.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interval', full_name='org.ga4gh.vmc.Position.interval', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _POSITION_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=371,
)


_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='org.ga4gh.vmc.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='org.ga4gh.vmc.Location.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sequence_id', full_name='org.ga4gh.vmc.Location.sequence_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='org.ga4gh.vmc.Location.position', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=459,
)


_ALLELE = _descriptor.Descriptor(
  name='Allele',
  full_name='org.ga4gh.vmc.Allele',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='org.ga4gh.vmc.Allele.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location_id', full_name='org.ga4gh.vmc.Allele.location_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='replacement', full_name='org.ga4gh.vmc.Allele.replacement', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=461,
  serialized_end=523,
)


_HAPLOTYPE = _descriptor.Descriptor(
  name='Haplotype',
  full_name='org.ga4gh.vmc.Haplotype',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='org.ga4gh.vmc.Haplotype.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sequence_id', full_name='org.ga4gh.vmc.Haplotype.sequence_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='context', full_name='org.ga4gh.vmc.Haplotype.context', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='allele_ids', full_name='org.ga4gh.vmc.Haplotype.allele_ids', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=525,
  serialized_end=630,
)


_GENOTYPE = _descriptor.Descriptor(
  name='Genotype',
  full_name='org.ga4gh.vmc.Genotype',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='org.ga4gh.vmc.Genotype.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='haplotype_ids', full_name='org.ga4gh.vmc.Genotype.haplotype_ids', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=632,
  serialized_end=677,
)

_SEQUENCEIDENTIFIER.fields_by_name['identifier'].message_type = _IDENTIFIER
_POSITION.fields_by_name['type'].enum_type = _POSITION_TYPE
_POSITION.fields_by_name['interval'].message_type = _INTERVAL
_POSITION_TYPE.containing_type = _POSITION
_LOCATION.fields_by_name['position'].message_type = _POSITION
_HAPLOTYPE.fields_by_name['context'].enum_type = _CONTEXT
DESCRIPTOR.message_types_by_name['Identifier'] = _IDENTIFIER
DESCRIPTOR.message_types_by_name['Sequence'] = _SEQUENCE
DESCRIPTOR.message_types_by_name['SequenceIdentifier'] = _SEQUENCEIDENTIFIER
DESCRIPTOR.message_types_by_name['Interval'] = _INTERVAL
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.message_types_by_name['Location'] = _LOCATION
DESCRIPTOR.message_types_by_name['Allele'] = _ALLELE
DESCRIPTOR.message_types_by_name['Haplotype'] = _HAPLOTYPE
DESCRIPTOR.message_types_by_name['Genotype'] = _GENOTYPE
DESCRIPTOR.enum_types_by_name['Context'] = _CONTEXT

Identifier = _reflection.GeneratedProtocolMessageType('Identifier', (_message.Message,), dict(
  DESCRIPTOR = _IDENTIFIER,
  __module__ = 'vmc_pb2'
  # @@protoc_insertion_point(class_scope:org.ga4gh.vmc.Identifier)
  ))
_sym_db.RegisterMessage(Identifier)

Sequence = _reflection.GeneratedProtocolMessageType('Sequence', (_message.Message,), dict(
  DESCRIPTOR = _SEQUENCE,
  __module__ = 'vmc_pb2'
  # @@protoc_insertion_point(class_scope:org.ga4gh.vmc.Sequence)
  ))
_sym_db.RegisterMessage(Sequence)

SequenceIdentifier = _reflection.GeneratedProtocolMessageType('SequenceIdentifier', (_message.Message,), dict(
  DESCRIPTOR = _SEQUENCEIDENTIFIER,
  __module__ = 'vmc_pb2'
  # @@protoc_insertion_point(class_scope:org.ga4gh.vmc.SequenceIdentifier)
  ))
_sym_db.RegisterMessage(SequenceIdentifier)

Interval = _reflection.GeneratedProtocolMessageType('Interval', (_message.Message,), dict(
  DESCRIPTOR = _INTERVAL,
  __module__ = 'vmc_pb2'
  # @@protoc_insertion_point(class_scope:org.ga4gh.vmc.Interval)
  ))
_sym_db.RegisterMessage(Interval)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), dict(
  DESCRIPTOR = _POSITION,
  __module__ = 'vmc_pb2'
  # @@protoc_insertion_point(class_scope:org.ga4gh.vmc.Position)
  ))
_sym_db.RegisterMessage(Position)

Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), dict(
  DESCRIPTOR = _LOCATION,
  __module__ = 'vmc_pb2'
  # @@protoc_insertion_point(class_scope:org.ga4gh.vmc.Location)
  ))
_sym_db.RegisterMessage(Location)

Allele = _reflection.GeneratedProtocolMessageType('Allele', (_message.Message,), dict(
  DESCRIPTOR = _ALLELE,
  __module__ = 'vmc_pb2'
  # @@protoc_insertion_point(class_scope:org.ga4gh.vmc.Allele)
  ))
_sym_db.RegisterMessage(Allele)

Haplotype = _reflection.GeneratedProtocolMessageType('Haplotype', (_message.Message,), dict(
  DESCRIPTOR = _HAPLOTYPE,
  __module__ = 'vmc_pb2'
  # @@protoc_insertion_point(class_scope:org.ga4gh.vmc.Haplotype)
  ))
_sym_db.RegisterMessage(Haplotype)

Genotype = _reflection.GeneratedProtocolMessageType('Genotype', (_message.Message,), dict(
  DESCRIPTOR = _GENOTYPE,
  __module__ = 'vmc_pb2'
  # @@protoc_insertion_point(class_scope:org.ga4gh.vmc.Genotype)
  ))
_sym_db.RegisterMessage(Genotype)


# @@protoc_insertion_point(module_scope)
