# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='types.proto',
  package='',
  serialized_pb=_b('\n\x0btypes.proto\"\xc5\x01\n\x11SequenceReference\x12/\n\tnamespace\x18\x01 \x02(\x0e\x32\x1c.SequenceReference.Namespace\x12\x11\n\taccession\x18\x02 \x02(\t\"l\n\tNamespace\x12\x08\n\x04NCBI\x10\x00\x12\x0b\n\x07\x45NSEMBL\x10\x01\x12\x07\n\x03LRG\x10\x02\x12\x07\n\x03MD5\x10\x64\x12\x08\n\x04SHA1\x10\x65\x12\n\n\x06SHA256\x10\x66\x12\n\n\x06SHA512\x10g\x12\n\n\x06SEGUID\x10n\x12\x08\n\x04TD24\x10o\"&\n\x08Interval\x12\r\n\x05start\x18\x01 \x02(\x04\x12\x0b\n\x03\x65nd\x18\x02 \x02(\x04\"@\n\x0cIntervalEdit\x12\x1b\n\x08location\x18\x01 \x02(\x0b\x32\t.Interval\x12\x13\n\x0breplacement\x18\x02 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SEQUENCEREFERENCE_NAMESPACE = _descriptor.EnumDescriptor(
  name='Namespace',
  full_name='SequenceReference.Namespace',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NCBI', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENSEMBL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LRG', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MD5', index=3, number=100,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHA1', index=4, number=101,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHA256', index=5, number=102,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHA512', index=6, number=103,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEGUID', index=7, number=110,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TD24', index=8, number=111,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=105,
  serialized_end=213,
)
_sym_db.RegisterEnumDescriptor(_SEQUENCEREFERENCE_NAMESPACE)


_SEQUENCEREFERENCE = _descriptor.Descriptor(
  name='SequenceReference',
  full_name='SequenceReference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespace', full_name='SequenceReference.namespace', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accession', full_name='SequenceReference.accession', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SEQUENCEREFERENCE_NAMESPACE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=213,
)


_INTERVAL = _descriptor.Descriptor(
  name='Interval',
  full_name='Interval',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='Interval.start', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='Interval.end', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=253,
)


_INTERVALEDIT = _descriptor.Descriptor(
  name='IntervalEdit',
  full_name='IntervalEdit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='IntervalEdit.location', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='replacement', full_name='IntervalEdit.replacement', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=319,
)

_SEQUENCEREFERENCE.fields_by_name['namespace'].enum_type = _SEQUENCEREFERENCE_NAMESPACE
_SEQUENCEREFERENCE_NAMESPACE.containing_type = _SEQUENCEREFERENCE
_INTERVALEDIT.fields_by_name['location'].message_type = _INTERVAL
DESCRIPTOR.message_types_by_name['SequenceReference'] = _SEQUENCEREFERENCE
DESCRIPTOR.message_types_by_name['Interval'] = _INTERVAL
DESCRIPTOR.message_types_by_name['IntervalEdit'] = _INTERVALEDIT

SequenceReference = _reflection.GeneratedProtocolMessageType('SequenceReference', (_message.Message,), dict(
  DESCRIPTOR = _SEQUENCEREFERENCE,
  __module__ = 'types_pb2'
  # @@protoc_insertion_point(class_scope:SequenceReference)
  ))
_sym_db.RegisterMessage(SequenceReference)

Interval = _reflection.GeneratedProtocolMessageType('Interval', (_message.Message,), dict(
  DESCRIPTOR = _INTERVAL,
  __module__ = 'types_pb2'
  # @@protoc_insertion_point(class_scope:Interval)
  ))
_sym_db.RegisterMessage(Interval)

IntervalEdit = _reflection.GeneratedProtocolMessageType('IntervalEdit', (_message.Message,), dict(
  DESCRIPTOR = _INTERVALEDIT,
  __module__ = 'types_pb2'
  # @@protoc_insertion_point(class_scope:IntervalEdit)
  ))
_sym_db.RegisterMessage(IntervalEdit)


# @@protoc_insertion_point(module_scope)
