# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vmc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vmc.proto',
  package='org.ga4gh.vmc',
  syntax='proto3',
  serialized_pb=_b('\n\tvmc.proto\x12\rorg.ga4gh.vmc\"9\n\x11SequenceReference\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x11\n\taccession\x18\x02 \x01(\t\"&\n\x08Interval\x12\r\n\x05start\x18\x01 \x01(\x04\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x04\"N\n\x0cIntervalEdit\x12)\n\x08location\x18\x01 \x01(\x0b\x32\x17.org.ga4gh.vmc.Interval\x12\x13\n\x0breplacement\x18\x02 \x01(\t\"\x86\x01\n\x06\x41llele\x12\x30\n\x06seqref\x18\x01 \x01(\x0b\x32 .org.ga4gh.vmc.SequenceReference\x12)\n\x08interval\x18\x02 \x01(\x0b\x32\x17.org.ga4gh.vmc.Interval\x12\x13\n\x0breplacement\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\t\"*\n\x08Genotype\x12\x12\n\nallele_ids\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\"+\n\tHaplotype\x12\x12\n\nallele_ids\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SEQUENCEREFERENCE = _descriptor.Descriptor(
  name='SequenceReference',
  full_name='org.ga4gh.vmc.SequenceReference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespace', full_name='org.ga4gh.vmc.SequenceReference.namespace', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accession', full_name='org.ga4gh.vmc.SequenceReference.accession', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=85,
)


_INTERVAL = _descriptor.Descriptor(
  name='Interval',
  full_name='org.ga4gh.vmc.Interval',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='org.ga4gh.vmc.Interval.start', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='org.ga4gh.vmc.Interval.end', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=125,
)


_INTERVALEDIT = _descriptor.Descriptor(
  name='IntervalEdit',
  full_name='org.ga4gh.vmc.IntervalEdit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='org.ga4gh.vmc.IntervalEdit.location', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='replacement', full_name='org.ga4gh.vmc.IntervalEdit.replacement', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=205,
)


_ALLELE = _descriptor.Descriptor(
  name='Allele',
  full_name='org.ga4gh.vmc.Allele',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seqref', full_name='org.ga4gh.vmc.Allele.seqref', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interval', full_name='org.ga4gh.vmc.Allele.interval', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='replacement', full_name='org.ga4gh.vmc.Allele.replacement', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='org.ga4gh.vmc.Allele.id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=342,
)


_GENOTYPE = _descriptor.Descriptor(
  name='Genotype',
  full_name='org.ga4gh.vmc.Genotype',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='allele_ids', full_name='org.ga4gh.vmc.Genotype.allele_ids', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='org.ga4gh.vmc.Genotype.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=386,
)


_HAPLOTYPE = _descriptor.Descriptor(
  name='Haplotype',
  full_name='org.ga4gh.vmc.Haplotype',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='allele_ids', full_name='org.ga4gh.vmc.Haplotype.allele_ids', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='org.ga4gh.vmc.Haplotype.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=431,
)

_INTERVALEDIT.fields_by_name['location'].message_type = _INTERVAL
_ALLELE.fields_by_name['seqref'].message_type = _SEQUENCEREFERENCE
_ALLELE.fields_by_name['interval'].message_type = _INTERVAL
DESCRIPTOR.message_types_by_name['SequenceReference'] = _SEQUENCEREFERENCE
DESCRIPTOR.message_types_by_name['Interval'] = _INTERVAL
DESCRIPTOR.message_types_by_name['IntervalEdit'] = _INTERVALEDIT
DESCRIPTOR.message_types_by_name['Allele'] = _ALLELE
DESCRIPTOR.message_types_by_name['Genotype'] = _GENOTYPE
DESCRIPTOR.message_types_by_name['Haplotype'] = _HAPLOTYPE

SequenceReference = _reflection.GeneratedProtocolMessageType('SequenceReference', (_message.Message,), dict(
  DESCRIPTOR = _SEQUENCEREFERENCE,
  __module__ = 'vmc_pb2'
  # @@protoc_insertion_point(class_scope:org.ga4gh.vmc.SequenceReference)
  ))
_sym_db.RegisterMessage(SequenceReference)

Interval = _reflection.GeneratedProtocolMessageType('Interval', (_message.Message,), dict(
  DESCRIPTOR = _INTERVAL,
  __module__ = 'vmc_pb2'
  # @@protoc_insertion_point(class_scope:org.ga4gh.vmc.Interval)
  ))
_sym_db.RegisterMessage(Interval)

IntervalEdit = _reflection.GeneratedProtocolMessageType('IntervalEdit', (_message.Message,), dict(
  DESCRIPTOR = _INTERVALEDIT,
  __module__ = 'vmc_pb2'
  # @@protoc_insertion_point(class_scope:org.ga4gh.vmc.IntervalEdit)
  ))
_sym_db.RegisterMessage(IntervalEdit)

Allele = _reflection.GeneratedProtocolMessageType('Allele', (_message.Message,), dict(
  DESCRIPTOR = _ALLELE,
  __module__ = 'vmc_pb2'
  # @@protoc_insertion_point(class_scope:org.ga4gh.vmc.Allele)
  ))
_sym_db.RegisterMessage(Allele)

Genotype = _reflection.GeneratedProtocolMessageType('Genotype', (_message.Message,), dict(
  DESCRIPTOR = _GENOTYPE,
  __module__ = 'vmc_pb2'
  # @@protoc_insertion_point(class_scope:org.ga4gh.vmc.Genotype)
  ))
_sym_db.RegisterMessage(Genotype)

Haplotype = _reflection.GeneratedProtocolMessageType('Haplotype', (_message.Message,), dict(
  DESCRIPTOR = _HAPLOTYPE,
  __module__ = 'vmc_pb2'
  # @@protoc_insertion_point(class_scope:org.ga4gh.vmc.Haplotype)
  ))
_sym_db.RegisterMessage(Haplotype)


# @@protoc_insertion_point(module_scope)
